class Dog {
    String name;
    int age;
}

public class ObjectExample {
    public static void main(String[] args) {
        // Generated by Github Copilot
        Dog dog1 = new Dog();
        dog1.name = "Buddy";
        dog1.age = 2;

        Dog dog2 = new Dog();
        dog2.name = "Max";
        dog2.age = 3;

        System.out.println(dog1.name + " is " + dog1.age + " years old.");
        System.out.println(dog2.name + " is " + dog2.age + " years old.");
    }
}
